In [2]:
import numpy as np
import pandas as pd

In [3]:
cbsa2msa = pd.read_csv('../../Data/crosswalks/cbsa_msa_crosswalk.csv',
                      dtype = {'cbsa': object, 'msa': object, 'fipst': object, 'fipscounty':object, 'ssacounty':object})

In [4]:
cbsa2msa = cbsa2msa.loc[:, [c for c in cbsa2msa.columns if 'y20' not in c]]
cbsa2msa

,countyname,state,ssacounty,fipscounty,msa,l,msaname,cbsa,cbsaname,cbsaold,cbsanameold,ssast,fipst
0,AUTAUGA,AL,01000,01001,5240,NaN,"MONTGOMERY, AL",33860,"Montgomery, AL",33860.0,"Montgomery, AL",1,01
1,BALDWIN,AL,01010,01003,5160,NaN,"MOBILE, AL",NaN,NaN,NaN,NaN,1,01
2,BARBOUR,AL,01020,01005,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
3,BIBB,AL,01030,01007,01,NaN,ALABAMA,13820,"Birmingham-Hoover, AL",13820.0,"Birmingham-Hoover, AL",1,01
4,BLOUNT,AL,01040,01009,1000,NaN,"BIRMINGHAM, AL",13820,"Birmingham-Hoover, AL",13820.0,"Birmingham-Hoover, AL",1,01
5,BULLOCK,AL,01050,01011,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
6,BUTLER,AL,01060,01013,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
7,CALHOUN,AL,01070,01015,0450,NaN,"ANNISTON,AL",11500,"Anniston-Oxford, AL",11500.0,"Anniston-Oxford, AL",1,01
8,CHAMBERS,AL,01080,01017,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
9,CHEROKEE,AL,01090,01019,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
10,CHILTON,AL,01100,01021,01,NaN,ALABAMA,13820,"Birmingham-Hoover, AL",13820.0,"Birmingham-Hoover, AL",1,01
11,CHOCTAW,AL,01110,01023,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
12,CLARKE,AL,01120,01025,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
13,CLAY,AL,01130,01027,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
14,CLEBURNE,AL,01140,01029,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
15,COFFEE,AL,01150,01031,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
16,COLBERT,AL,01160,01033,2650,NaN,"FLORENCE, AL",22520,"Florence-Muscle Shoals, AL",22520.0,"Florence-Muscle Shoals, AL",1,01
17,CONECUH,AL,01170,01035,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
18,COOSA,AL,01180,01037,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
19,COVINGTON,AL,01190,01039,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
20,CRENSHAW,AL,01200,01041,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
21,CULLMAN,AL,01210,01043,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
22,DALE,AL,01220,01045,2180,NaN,"DOTHAN, AL",NaN,NaN,NaN,NaN,1,01
23,DALLAS,AL,01230,01047,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
24,DE KALB,AL,01240,01049,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
25,ELMORE,AL,01250,01051,5240,NaN,"MONTGOMERY, AL",33860,"Montgomery, AL",33860.0,"Montgomery, AL",1,01
26,ESCAMBIA,AL,01260,01053,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
27,ETOWAH,AL,01270,01055,2880,NaN,"GADSDEN, AL",23460,"Gadsden, AL",23460.0,"Gadsden, AL",1,01
28,FAYETTE,AL,01280,01057,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
29,FRANKLIN,AL,01290,01059,01,NaN,ALABAMA,NaN,NaN,NaN,NaN,1,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3263,MAYAGUEZ,PR,40480,72097,4840,NaN,"MAYAGUEZ, PR",32420,"MayagÃ¼ez, PR",32420.0,"Mayaguez, PR",40,72
3264,MOCA,PR,40490,72099,0060,NaN,"AGUADILLA, PR",10380,"Aguadilla-Isabela-San SebastiÃ¡n, PR",10380.0,"Aguadilla-Isabela-San Sebastian, PR",40,72
3265,MOROVIS,PR,40500,72101,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3266,MAGUABO,PR,40510,72103,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3267,NARANJITO,PR,40520,72105,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3268,OROCOVIS,PR,40530,72107,40,NaN,PUERTO RICO,41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3269,PATILLAS,PR,40540,72109,40,NaN,PUERTO RICO,25020,"Guayama, PR",25020.0,"Guayama, PR",40,72
3270,PENUELAS,PR,40550,72111,6360,NaN,"PONCE, PR",49500,"Yauco, PR",49500.0,"Yauco, PR",40,72
3271,PONCE,PR,40560,72113,6360,NaN,"PONCE, PR",38660,"Ponce, PR",38660.0,"Ponce, PR",40,72
3272,QUEBRADILLAS,PR,40570,72115,40,NaN,PUERTO RICO,41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3273,RINCON,PR,40580,72117,40,NaN,PUERTO RICO,10380,"Aguadilla-Isabela-San SebastiÃ¡n, PR",10380.0,"Aguadilla-Isabela-San Sebastian, PR",40,72
3274,RIO GRANDE,PR,40590,72119,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3275,SABANA GRANDE,PR,40610,72121,4840,NaN,"MAYAGUEZ, PR",41900,"San GermÃ¡n-Cabo Rojo, PR",41900.0,"San German-Cabo Rojo, PR",40,72
3276,SALINAS,PR,40620,72123,40,NaN,PUERTO RICO,NaN,NaN,NaN,NaN,40,72
3277,SAN GERMAN,PR,40630,72125,4840,NaN,"MAYAGUEZ, PR",41900,"San GermÃ¡n-Cabo Rojo, PR",41900.0,"San German-Cabo Rojo, PR",40,72
3278,SAN JUAN,PR,40640,72127,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3279,SAN LORENZO,PR,40650,72129,1310,NaN,"CAGUAS, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3280,SAN SEBASTIAN,PR,40660,72131,40,NaN,PUERTO RICO,10380,"Aguadilla-Isabela-San SebastiÃ¡n, PR",10380.0,"Aguadilla-Isabela-San Sebastian, PR",40,72
3281,SANTA ISABEL,PR,40670,72133,40,NaN,PUERTO RICO,NaN,NaN,NaN,NaN,40,72
3282,TOA ALTA,PR,40680,72135,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3283,TOA BAJA,PR,40690,72137,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3284,TRUJILLO ALTO,PR,40700,72139,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3285,UTUADO,PR,40710,72141,40,NaN,PUERTO RICO,NaN,NaN,NaN,NaN,40,72
3286,VEGA ALTA,PR,40720,72143,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3287,VEGA BAJA,PR,40730,72145,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3288,VIEQUES,PR,40740,72147,40,NaN,PUERTO RICO,NaN,NaN,NaN,NaN,40,72
3289,VILLALBA,PR,40750,72149,6360,NaN,"PONCE, PR",38660,"Ponce, PR",38660.0,"Ponce, PR",40,72
3290,YABUCOA,PR,40760,72151,7440,L,"SAN JUAN-BAYAMON, PR",41980,"San Juan-Caguas-Guaynabo, PR",41980.0,"San Juan-Caguas-Guaynabo, PR",40,72
3291,YAUCO,PR,40770,72153,6360,NaN,"PONCE, PR",49500,"Yauco, PR",49500.0,"Yauco, PR",40,72
3292,"PUERTO RICO, NFD",PR,40999,72990,40,NaN,PUERTO RICO,NaN,NaN,NaN,NaN,40,72

In [5]:
fips = pd.read_csv('../../Data/crosswalks/ucr_fips_msa.csv', header=None, 
                   names= ['state', 'stategips', 'ucrfips', 'countyname', 'zoning'],
                   dtype = {'ucrfips': object, 'stategips': object})
def county_remover(x):
    return ' '.join(x.split(' ')[:-1]).upper()

fips.countyname = fips.countyname.apply(county_remover)
fips.head()

  state stategips ucrfips countyname zoning
0    AL        01     001    AUTAUGA     H1
1    AL        01     003    BALDWIN     H1
2    AL        01     005    BARBOUR     H1
3    AL        01     007       BIBB     H1
4    AL        01     009     BLOUNT     H1

In [6]:
mdf = pd.merge(fips, cbsa2msa, on=['countyname', 'state'])

In [58]:
mdf[mdf.countyname == 'CLARK'].loc[:, ['countyname', 'cbsa', 'cbsaname', 'state']]

     countyname   cbsa                             cbsaname state
98        CLARK    NaN                                  NaN    AR
541       CLARK    NaN                                  NaN    ID
580       CLARK    NaN                                  NaN    IL
674       CLARK  31140                    Louisville, KY-IN    IN
865       CLARK    NaN                                  NaN    KS
982       CLARK  30460                Lexington-Fayette, KY    KY
1456      CLARK    NaN                                  NaN    MO
1695      CLARK  29820               Las Vegas-Paradise, NV    NV
1998      CLARK  44220                      Springfield, OH    OH
2315      CLARK    NaN                                  NaN    SD
2858      CLARK  38900  Portland-Vancouver-Beaverton, OR-WA    WA
2955      CLARK    NaN                                  NaN    WI

# Now I need to load my data with the cbsa

In [53]:
cbsadf = pd.read_csv('../../Data/crosswalks/cities_gt_50k_cbsa.csv', dtype = {'CBSA': object})
cbsadf.columns = ['City', 'State', 'cbsa']
cbsadf.head()

          City State   cbsa
0   Montgomery    AL  33860
1        Miami    FL  33124
2  Minneapolis    MN  33460
3      SanJose    CA  41940
4       Newark    NJ  35084

In [54]:
fullmerge = pd.merge(cbsadf, mdf, on='cbsa')
fullmerge.head()

,City,State,cbsa,state,stategips,ucrfips,countyname,zoning,ssacounty,fipscounty,msa,l,msaname,cbsaname,cbsaold,cbsanameold,ssast,fipst
0,Montgomery,AL,33860,AL,01,001,AUTAUGA,H1,01000,01001,5240,NaN,"MONTGOMERY, AL","Montgomery, AL",33860.0,"Montgomery, AL",1,01
1,Montgomery,AL,33860,AL,01,051,ELMORE,H1,01250,01051,5240,NaN,"MONTGOMERY, AL","Montgomery, AL",33860.0,"Montgomery, AL",1,01
2,Montgomery,AL,33860,AL,01,085,LOWNDES,H1,01420,01085,01,NaN,ALABAMA,"Montgomery, AL",33860.0,"Montgomery, AL",1,01
3,Montgomery,AL,33860,AL,01,101,MONTGOMERY,H1,01500,01101,5240,NaN,"MONTGOMERY, AL","Montgomery, AL",33860.0,"Montgomery, AL",1,01
4,Miami,FL,33124,FL,12,086,MIAMI-DADE,H1,10120,12086,5000,L,"MIAMI, FL","Miami-Miami Beach-Kendall, FL",33124.0,"Miami-Miami Beach-Kendall, FL",10,12

In [55]:
coi = ['City', 'State', 'fipst', 'stategips', 'ucrfips', 'fipscounty', 'cbsa', 'msa', 'ssast']

fullmerge.loc[:, coi].to_csv('../../Data/crosswalks/city_msa_crosswalk.csv')

In [56]:
for c in ['Buffalo', 'Spokane', 'Tacoma', 'Reno', 'Mobile', 'Tucson', 'Miami', \
          'Seattle', 'Pittsburgh', 'LosAngeles', 'Jacksonville', 'Warren', 'Detroit']:
    print(c)
    print(fullmerge[fullmerge.City==c])
    print('----')

Buffalo
        City State   cbsa state stategips ucrfips countyname zoning ssacounty  \
259  Buffalo    NY  15380    NY        36     029       ERIE     H1     33240
260  Buffalo    NY  15380    NY        36     063    NIAGARA     H1     33500

    fipscounty   msa  l                    msaname                   cbsaname  \
259      36029  1280  L  BUFFALO-NIAGARA FALLS, NY  Buffalo-Niagara Falls, NY
260      36063  1280  L  BUFFALO-NIAGARA FALLS, NY  Buffalo-Niagara Falls, NY

     cbsaold                cbsanameold  ssast fipst
259  15380.0  Buffalo-Niagara Falls, NY     33    36
260  15380.0  Buffalo-Niagara Falls, NY     33    36
----
Spokane
        City State   cbsa state stategips ucrfips countyname zoning ssacounty  \
148  Spokane    WA  44060    WA        53     063    SPOKANE     H1     50310

    fipscounty   msa    l      msaname     cbsaname  cbsaold  cbsanameold  \
148      53063  7840  NaN  SPOKANE, WA  Spokane, WA  44060.0  Spokane, WA

     ssast fipst
148     50    53
----
Tacoma
       City State   cbsa state stategips ucrfips countyname zoning ssacounty  \
342  Tacoma    WA  45104    WA        53     053     PIERCE     H1     50260

    fipscounty   msa    l     msaname    cbsaname  cbsaold cbsanameold  ssast  \
342      53053  8200  NaN  TACOMA, WA  Tacoma, WA  45104.0  Tacoma, WA     50

    fipst
342    53
----
Reno
     City State   cbsa state stategips ucrfips countyname zoning ssacounty  \
125  Reno    NV  39900    NV        32     029     STOREY     H1     29140
126  Reno    NV  39900    NV        32     031     WASHOE     H1     29150

    fipscounty   msa    l   msaname         cbsaname  cbsaold  \
125      32029    29  NaN    NEVADA  Reno-Sparks, NV  39900.0
126      32031  6720  NaN  RENO, NV  Reno-Sparks, NV  39900.0

         cbsanameold  ssast fipst
125  Reno-Sparks, NV     29    32
126  Reno-Sparks, NV     29    32
----
Mobile
       City State   cbsa state stategips ucrfips countyname zoning ssacounty  \
282  Mobile    AL  33660    AL        01     097     MOBILE     H1     01480

    fipscounty   msa    l     msaname    cbsaname  cbsaold cbsanameold  ssast  \
282      01097  5160  NaN  MOBILE, AL  Mobile, AL  33660.0  Mobile, AL      1

    fipst
282    01
----
Tucson
       City State   cbsa state stategips ucrfips countyname zoning ssacounty  \
237  Tucson    AZ  46060    AZ        04     019       PIMA     H1     03090

    fipscounty   msa    l     msaname    cbsaname  cbsaold cbsanameold  ssast  \
237      04019  8520  NaN  TUCSON, AZ  Tucson, AZ  46060.0  Tucson, AZ      3

    fipst
237    04
----
Miami
    City State   cbsa state stategips ucrfips  countyname zoning ssacounty  \
4  Miami    FL  33124    FL        12     086  MIAMI-DADE     H1     10120

  fipscounty   msa  l    msaname                       cbsaname  cbsaold  \
4      12086  5000  L  MIAMI, FL  Miami-Miami Beach-Kendall, FL  33124.0

                     cbsanameold  ssast fipst
4  Miami-Miami Beach-Kendall, FL     10    12
----
Seattle
        City State   cbsa state stategips ucrfips countyname zoning ssacounty  \
149  Seattle    WA  42644    WA        53     033       KING     H1     50160
150  Seattle    WA  42644    WA        53     061  SNOHOMISH     H1     50300

    fipscounty   msa  l                       msaname  \
149      53033  7600  L  SEATTLE-BELLEVUE-EVERETT, WA
150      53061  7600  L  SEATTLE-BELLEVUE-EVERETT, WA

                         cbsaname  cbsaold                   cbsanameold  \
149  Seattle-Bellevue-Everett, WA  42644.0  Seattle-Bellevue-Everett, WA
150  Seattle-Bellevue-Everett, WA  42644.0  Seattle-Bellevue-Everett, WA

     ssast fipst
149     50    53
150     50    53
----
Pittsburgh
           City State   cbsa state stategips ucrfips    countyname zoning  \
267  Pittsburgh    PA  38300    PA        42     003     ALLEGHENY     H1
268  Pittsburgh    PA  38300    PA        42     005     ARMSTRONG     H1
269  Pittsburgh    PA  38300    PA        42     007        BEAVER     H1
270  Pittsburgh    PA  38300    PA        42     019        BUTLER     H1
271  Pittsburgh    PA  38300    PA        42     051       FAYETTE     H1
272  Pittsburgh    PA  38300    PA        42     125    WASHINGTON     H1
273  Pittsburgh    PA  38300    PA        42     129  WESTMORELAND     H1

    ssacounty fipscounty   msa    l         msaname        cbsaname  cbsaold  \
267     39010      42003  6280    L  PITTSBURGH, PA  Pittsburgh, PA  38300.0
268     39070      42005    39  NaN    PENNSYLVANIA  Pittsburgh, PA  38300.0
269     39080      42007  6280    L  PITTSBURGH, PA  Pittsburgh, PA  38300.0
270     39150      42019  6280    L  PITTSBURGH, PA  Pittsburgh, PA  38300.0
271     39330      42051  6280    L  PITTSBURGH, PA  Pittsburgh, PA  38300.0
272     39750      42125  6280    L  PITTSBURGH, PA  Pittsburgh, PA  38300.0
273     39770      42129  6280    L  PITTSBURGH, PA  Pittsburgh, PA  38300.0

        cbsanameold  ssast fipst
267  Pittsburgh, PA     39    42
268  Pittsburgh, PA     39    42
269  Pittsburgh, PA     39    42
270  Pittsburgh, PA     39    42
271  Pittsburgh, PA     39    42
272  Pittsburgh, PA     39    42
273  Pittsburgh, PA     39    42
----
LosAngeles
           City State   cbsa state stategips ucrfips   countyname zoning  \
317  LosAngeles    CA  31084    CA        06     037  LOS ANGELES     H1
318  LosAngeles    CA  31084    CA        06     037  LOS ANGELES     H1

    ssacounty fipscounty   msa  l                     msaname  \
317     05200      06037  4480  L  LOS ANGELES-LONG BEACH, CA
318     05210      06037  4480  L  LOS ANGELES-LONG BEACH, CA

                                 cbsaname  cbsaold  \
317  Los Angeles-Long Beach-Santa Ana, CA  31084.0
318  Los Angeles-Long Beach-Santa Ana, CA  31084.0

                             cbsanameold  ssast fipst
317  Los Angeles-Long Beach-Glendale, CA      5    06
318  Los Angeles-Long Beach-Glendale, CA      5    06
----
Jacksonville
             City State   cbsa state stategips ucrfips countyname zoning  \
131  Jacksonville    FL  27260    FL        12     003      BAKER     H1
132  Jacksonville    FL  27260    FL        12     019       CLAY     H1
133  Jacksonville    FL  27260    FL        12     031      DUVAL     H6
134  Jacksonville    FL  27260    FL        12     089     NASSAU     H1
135  Jacksonville    FL  27260    FL        12     109  ST. JOHNS     H1

    ssacounty fipscounty   msa    l           msaname          cbsaname  \
131     10010      12003    10  NaN           FLORIDA  Jacksonville, FL
132     10090      12019  3600    L  JACKSONVILLE, FL  Jacksonville, FL
133     10150      12031  3600    L  JACKSONVILLE, FL  Jacksonville, FL
134     10440      12089  3600    L  JACKSONVILLE, FL  Jacksonville, FL
135     10540      12109  3600    L  JACKSONVILLE, FL  Jacksonville, FL

     cbsaold       cbsanameold  ssast fipst
131  27260.0  Jacksonville, FL     10    12
132  27260.0  Jacksonville, FL     10    12
133  27260.0  Jacksonville, FL     10    12
134  27260.0  Jacksonville, FL     10    12
135  27260.0  Jacksonville, FL     10    12
----
Warren
       City State   cbsa state stategips ucrfips  countyname zoning ssacounty  \
319  Warren    MI  47644    MI        26     087      LAPEER     H1     23430
320  Warren    MI  47644    MI        26     093  LIVINGSTON     H1     23460
321  Warren    MI  47644    MI        26     099      MACOMB     H1     23490
322  Warren    MI  47644    MI        26     125     OAKLAND     H1     23620
323  Warren    MI  47644    MI        26     147   ST. CLAIR     H1     23730

    fipscounty   msa    l        msaname                          cbsaname  \
319      26087  2160    L    DETROIT, MI  Warren-Farmington-Hills-Troy, MI
320      26093  0440  NaN  ANN ARBOR, MI  Warren-Farmington-Hills-Troy, MI
321      26099  2160    L    DETROIT, MI  Warren-Farmington-Hills-Troy, MI
322      26125  2160    L    DETROIT, MI  Warren-Farmington-Hills-Troy, MI
323      26147  2160    L    DETROIT, MI  Warren-Farmington-Hills-Troy, MI

     cbsaold                       cbsanameold  ssast fipst
319  47644.0  Warren-Troy-Farmington-Hills, MI     23    26
320  47644.0  Warren-Troy-Farmington-Hills, MI     23    26
321  47644.0  Warren-Troy-Farmington-Hills, MI     23    26
322  47644.0  Warren-Troy-Farmington-Hills, MI     23    26
323  47644.0  Warren-Troy-Farmington-Hills, MI     23    26
----
Detroit
        City State   cbsa state stategips ucrfips countyname zoning ssacounty  \
124  Detroit    MI  19804    MI        26     163      WAYNE     H1     23810

    fipscounty   msa  l      msaname                      cbsaname  cbsaold  \
124      26163  2160  L  DETROIT, MI  Detroit-Livonia-Dearborn, MI  19804.0

                      cbsanameold  ssast fipst
124  Detroit-Livonia-Dearborn, MI     23    26
----

79